### ISSUE TITLE
Standards

### ISSUE THREAD

**Issue by s0kil** [kazu-yamamoto/quic#1]
Hey @kazu-yamamoto, Are this goals of this library to comply with: [draft-ietf-quic-http](https://datatracker.ietf.org/doc/draft-ietf-quic-http) and [draft-ietf-quic-qpack](https://datatracker.ietf.org/doc/draft-ietf-quic-qpack) ?

**Comment by kazu-yamamoto** [comment]
The `quic` library should cover `quic-transport`, `quic-tls` and `quic-recovery`.
Probably, I will extend the `http2` library for `quic-http` and `quic-qpack`.

You can find QUIC APIs of TLS 1.3 here: https://github.com/kazu-yamamoto/hs-tls/tree/handshake-controller

**Comment by s0kil** [comment]
Does extending `http2` make sense in this case? Since QUIC is renamed to HTTP/3, maybe a new package?

**Comment by kazu-yamamoto** [comment]
I'm now sure at this moment. If I will feel that `http3` is better, I will make the new package.

**Comment by s0kil** [comment]
Thanks for the clarification.

**Comment by kazu-yamamoto** [comment]
I wrote `README.md`.
