### ISSUE TITLE
No packet header encryption

### ISSUE THREAD

**Issue by simonasmulevicius** [kazu-yamamoto/quic#10]
Good morning, 

I am doing a research project about the QUIC offloading in hardware.
For this reason, I would like to be able to see packet numbers (in hardware).
However, I know that multiple implementations of QUIC usually encrypt packet headers.
Hence, I wonder if this implementation of QUIC has an API to turn off packet header encryption mechanism.

Kind regards, 
Simonas

**Comment by kazu-yamamoto** [comment]
No such APIs at this moment.
