### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/quic#2]
The current target is draft-32.

## Handshake

- [x] QUIC APIs in the Haskell TLS library
- [x] Hello retry request
- [x] New session ticket
- [x] Killing the handshake controller with timeout in the client side
- [x] Key udpate

## Dispatching

- [x] NAT rebinding
- [x] Retry
- [x] Version negotiation
- [x] Path validation
- [x] Migration in the server side
- [x] Migration in the client side

## Transport

- [x] Encoder and decoder for packets and frames
- [x] Basic APIs for connections
- [x] Resending packets with PSQ
- [x] Fragmentations and defragmentations
- [x] Dispatching based on CID
- [x] Closing a stream by sending the Fin bit vs closing the connection
- [ ] The spin bit
- [x] 0RTT
  - [ ] Server checks early data size
  - [ ] Client resends early data in 1-RTT if rejected
- [x] Amplification attack prevention (the three times rule)

## HTTP/3 and QPACK

- [x] Toy client and server for HTTP/0.9 or ALPN=hq-draft_version
- [x] Toy client and server for HTTP/3 or ALPN=h3-draft_version
- [x] HTTP/3
- [x] QPACK
  - [x] Decoder
  - [x] Naive/Static encoder
  - [ ] Linear encoder (using dynamic table)
- [ ] Server push
- [x] Integrating to Warp (warp-quic)

## Logging

- [x] Debug logging 
- [x] qlog

## Recovery

- [x] Flow control
  - [x] Max data
  - [x] Max stream data
  - [x] Max streams
- [x] Loss detection
- [x] Congestion control

**Comment by bjin** [comment]
Really appreciate your work on this project. While it's absolutely at an early stage to discuss this, I'd like to ask about the plan regarding the congestion control algorithm.

The draft [recommends NewReno algorithm](https://tools.ietf.org/html/draft-ietf-quic-recovery-24#section-6), but alternative algorithm like bbr is supported by some implementation including [chromium](https://quiche.googlesource.com/quiche/+/refs/heads/master/quic/core/congestion_control/bbr_sender.cc) and [litespeed](https://fossies.org/linux/lsquic/src/liblsquic/lsquic_bbr.c). So my question is, is basic congestion control planned to be implemented, and if so, will it be extensible to support more algorithm in the future?

**Comment by kazu-yamamoto** [comment]
@bjin Congestion control would be the very *last* part of my implementation. Very far away... Anyway, it should be extensible if users want!

**Comment by kazu-yamamoto** [comment]
@bjin I have implemented the recovery draft finally but the code is not stable yet.

**Comment by kazu-yamamoto** [comment]
I believe that the current code is quite stable.
