### ISSUE TITLE
Connection timeout when using `127.0.0.2` as server address

### ISSUE THREAD

**Issue by jvanbruegge** [kazu-yamamoto/quic#36]
I wrote a simple server + client, that work as expected if I run them on the normal loopback address `127.0.0.1`.
But if I try to use `127.0.0.2`, the server tries to migrate something as soon as the client does a http3 request. This is the debug output:
```
Original CID: 9a12efad1a054aa9ae1960dd8469e5efa642
Packet size: 1252 (1252)
debug: dispatch: Migration: 127.0.0.1:55084 (0a0f719305f18407)
```
Netstat tells me that the server is listening on the corrrect IP and port. With the server on `127.0.0.1` I get:
```
Original CID: 3cc7296e1137de5938cb7a23ecd628896e
Packet size: 1252 (1252)
Version: Version 1
Cipher: AES256GCM-SHA384
ALPN: h3
Mode: FullHandshake
Local CID: df668537dd0e4a48
Remote CID:
Local SockAddr: 127.0.0.1:4433
Remote SockAddr: 127.0.0.1:50196
```
I tested `0.0.1` and the current master.

My settings code:
```haskell
mkServerConfig :: IO ServerConfig
mkServerConfig = do
  qlog <- lookupEnv "QLOGDIR"
  keylog <- getEnv "SSLKEYLOGFILE"
  writeFile keylog ""

  certDir <- getEnv "CERTS"
  cred <-
    credentialLoadX509 (certDir </> "cert.pem") (certDir </> "priv.key") >>= \case
      Left err -> error $ "Error while loading certificate: " <> err
      Right x -> pure x

  host <- read <$> getEnv "IP"
  port <- read <$> getEnv "PORT"

  pure $
    defaultServerConfig
      { scKeyLog = appendFile keylog . (<> "\n"),
        scQLog = qlog,
        scCredentials = Credentials [cred],
        scAddresses = [(host, port)],
        scALPN = Just . const . const . pure $ "h3",
        scDebugLog = Just "./debuglog"
      }

mkSettings :: IO Settings
mkSettings = do
  port <- read <$> getEnv "PORT"
  host <- fromString <$> getEnv "IP"

  putStrLn "HOST"
  print host

  pure $
    defaultSettings
      { settingsPort = port,
        settingsHost = host
      }
```

**Comment by jvanbruegge** [comment]
I tried to current master, but that does seems to not print a debug log at all, even when enabled.

**Comment by kazu-yamamoto** [comment]
I assume that you are using Linux. If you do `ping 127.0.0.2`, your Linux responds. But this does not mean that packets to 127.0.0.2 are received by applications. You should add 127.0.0.2 to the loopback interface somehow.

**Comment by jvanbruegge** [comment]
I did that using ifconfig, added a second loopback interface. And yes, I am indeed on Linux

**Comment by jvanbruegge** [comment]
I've dug a bit deeper and added various logging to `quic` and comparing the two outputs. They are similar as expected until after printing the packet size where the `.2` server gets a second `token == ""` packet in the `dispatch` function [here](https://github.com/kazu-yamamoto/quic/blob/6b9500c8057ac3d974a47543b74b5db11e29ecc0/Network/QUIC/Server/Reader.hs#L205). After that it goes one time in the catchall case [here](https://github.com/kazu-yamamoto/quic/blob/6b9500c8057ac3d974a47543b74b5db11e29ecc0/Network/QUIC/Server/Reader.hs#L333), then one time in the third case [here](https://github.com/kazu-yamamoto/quic/blob/6b9500c8057ac3d974a47543b74b5db11e29ecc0/Network/QUIC/Server/Reader.hs#L318) before repeatedly going into the catchall case again
When running on `.1` The dispatcher does not recieve a second `token == ""` packet and the program proceeds normally.

**Comment by jvanbruegge** [comment]
I've captured the packets with wireshark. After the first received packet on `.2` it answers from `.1` suddenly:
```
    1 0.000000000    127.0.0.1 → 127.0.0.2    QUIC 1294 Initial, DCID=8afb16d6f02fc1b1db6279cbaad6203eed, PKN: 0, PADDING, CRYPTO
    2 0.017900572    127.0.0.1 → 127.0.0.1    QUIC 1294 Handshake, SCID=864e6a83c8550d35
    3 0.018202414    127.0.0.1 → 127.0.0.1    QUIC 1294 Handshake, SCID=864e6a83c8550d35
    4 0.019427562    127.0.0.1 → 127.0.0.2    QUIC 1294 Initial, DCID=864e6a83c8550d35, PKN: 6409760
    5 0.019887976    127.0.0.1 → 127.0.0.2    QUIC 137 Handshake, DCID=864e6a83c8550d35
    6 0.020310250    127.0.0.1 → 127.0.0.2    QUIC 126 Protected Payload (KP0)
    7 0.076041028    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
    8 0.076142911    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
    9 0.188092080    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   10 0.188213877    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   11 0.410283644    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   12 0.410452542    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   13 0.853407107    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   14 0.853553299    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   15 1.018396740    127.0.0.1 → 127.0.0.1    QUIC 1294 Initial, SCID=864e6a83c8550d35, PKN: 40996
   16 1.739340791    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   17 1.739423814    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   18 3.510446470    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
   19 3.510545454    127.0.0.1 → 127.0.0.2    QUIC 132 Handshake, DCID=864e6a83c8550d35
```
With the server running on `.1` i get this output:
```
    1 0.000000000    127.0.0.1 → 127.0.0.1    QUIC 1294 Initial, DCID=b1a78e77f8221ed605645372de5e86bd53, PKN: 0, PADDING, CRYPTO
    2 0.012981822    127.0.0.1 → 127.0.0.1    QUIC 1294 Handshake, SCID=5007707f5e86a233
    3 0.013224086    127.0.0.1 → 127.0.0.1    QUIC 1294 Handshake, SCID=5007707f5e86a233
    4 0.014255965    127.0.0.1 → 127.0.0.1    QUIC 1294 Initial, DCID=5007707f5e86a233, PKN: 1, ACK, PADDING
    5 0.014807984    127.0.0.1 → 127.0.0.1    QUIC 137 Handshake, DCID=5007707f5e86a233
    6 0.015058470    127.0.0.1 → 127.0.0.1    QUIC 126 Protected Payload (KP0), DCID=5007707f5e86a233
    7 0.015688072    127.0.0.1 → 127.0.0.1    QUIC 1294 Protected Payload (KP0)
    8 0.015855481    127.0.0.1 → 127.0.0.1    QUIC 76 Protected Payload (KP0)
    9 0.017359173    127.0.0.1 → 127.0.0.1    QUIC 1294 Protected Payload (KP0)
   10 0.018074449    127.0.0.1 → 127.0.0.1    QUIC 1294 Protected Payload (KP0)
   11 0.018155001    127.0.0.1 → 127.0.0.1    QUIC 1294 Protected Payload (KP0)
   12 0.018340120    127.0.0.1 → 127.0.0.1    QUIC 74 Protected Payload (KP0)
   13 0.019117446    127.0.0.1 → 127.0.0.1    QUIC 73 Protected Payload (KP0)
```

**Comment by jvanbruegge** [comment]
Btw, the current master does not print the `debug: dispatch: Migration: 127.0.0.1:<some port> (<some id>)` line any more

**Comment by jvanbruegge** [comment]
I found a solution:
If I switch out `anysa` with `mysa` in `Socket.hs` ([here](https://github.com/kazu-yamamoto/quic/blob/master/Network/QUIC/Socket.hs#L38-L39)), everything works as expected.

**Comment by kazu-yamamoto** [comment]
@jvanbruegge What you found is a corner case where a network interface has multiple IP addresses of the same family. Thanks. In this case, it is possible that `connect` selects a wrong IP address. 

Your fix works only on Linux with a possible race condition and causes an error on BSD. I have no idea on how to fix it at this moment.

**Comment by kazu-yamamoto** [comment]
The current architecture opens a wildcard socket for every IP address:
- say: (127.0.0.1:443, \*:\*)

When a connected socket is created, `bind` with mysa (127.0.0.1:443) fails on BSD because the entries are duplicated:
- (127.0.0.1:443, \*:\*)

This duplication is allowed on Linux but I suspect a race condition because of duplication. So, the current idea is call `bind` with anysa (\*:443):
- (\*:443, \*:\*)

No duplication is created. So far, so good. Then call `connect` with peersa (pa:pp):
- (127.0.0.1:443, pa:pp)

If the interface has a single IP address, this works well. But if it has multiple IP addresses, it is not the case, unfortunately.

But I cannot remember why we open a wild socket for every IP address. Probably, I was influenced by BIND. 

Let's consider a new architecture that uses a single wildcard socket:
- (\*:443, \*:\*)

`bind` a new socket with myaddr resutls in:
- (127.0.0.1:443, \*:\*)

No duplication is created. OK. Then call `connect`:
-  (127.0.0.1:443, pa:pp)

This should work well even if a network address has multiple IP addresses. Now I'm looking for the reason why BIND has such architecture.

**Comment by kazu-yamamoto** [comment]
- Every IP (current)
  - Pros: safe settings is possible (e.g. Only 127.0.0.1:443 for local testing)
  - Cons: this bug exists
- Wildcard
  - Pros: this bug does not exists
  - Cons: safe setting is not possible

So, I guess that we should both modes. `udpServerConnectedSocket` should behave differently according to the mode.

Make sense?

**Comment by jvanbruegge** [comment]
> The current architecture opens a wildcard socket for every IP address: say: (127.0.0.1:443, *:*)

As far as I know socket/network programming if you create a socket is does not have any IP address associated with it. Only once you `bind` it, it will become associated with the IP.

So I think there needs to be one socket per address in `scAddresses` each of which are then bound to the address. So if I specify `["127.0.0.2:4433"]` it will only listen on that IP. Otherwise I would use `anysa` in `scAddresses`.

**Comment by kazu-yamamoto** [comment]
@jvanbruegge  Sorry but I don't understand the comment above. Basically, in UDP socket programming, we can bind either `*:4433` or `127.0.0.2:4433`. To create a connected socket which can co-exist the listen socket, we should implement a specifc strategy for each scenario (see above) because there is no `accept` for UDP. 

The current implementation supports the latter only. My proposal is to support the former, too.

**Comment by kazu-yamamoto** [comment]
#40, which should fix this issue, has been merged.
Please use `scPort` instead of `scAddresses`.
And please close this issue when you confirm the fix.

**Comment by kazu-yamamoto** [comment]
I removed `scPort` and restored `scAddresses`. Now you can specify "0.0.0.0" and "::" to `scAddresses` to fix this problem.
