### ISSUE TITLE
Feature Request: Implement server-side hooks for Server Name Indication (SNI) and Client Certificates

### ISSUE THREAD

**Issue by bjin** [kazu-yamamoto/quic#59]
The `tls` package offers a [`Network.TLS.ServerHooks`](https://hackage.haskell.org/package/tls-1.9.0/docs/Network-TLS.html#t:ServerHooks) parameter, allowing customization through functions like `onClientCertificate` and `onServerNameIndication` on the server side. Could we consider introducing a similar feature in this package?

It seems that the [`Network.QUIC.Internal.Hooks`](https://hackage.haskell.org/package/quic-0.1.12/docs/Network-QUIC-Internal.html#t:Hooks) parameter is primarily designed for debugging and may not offer significant value in real-world scenarios.

**Comment by kazu-yamamoto** [comment]
Such feature extensions are welcome.
Would you provide a flexible design?

**Comment by kazu-yamamoto** [comment]
Your approach should work.
If you want to know more, please read https://kazu-yamamoto.hatenablog.jp/entry/2020/09/16/150801

**Comment by kazu-yamamoto** [comment]
Probably, we should expose TLS's `ServerHooks` entirely from QUIC's `ServerConfig`.

**Comment by kazu-yamamoto** [comment]
May I ask you to implement it and send a PR?

**Comment by kazu-yamamoto** [comment]
> your warp-quic GitHub repository is outdated. 

I don't understand this. 
Do you mean that your warp-quic GitHub repository *will be* outdated.

**Comment by kazu-yamamoto** [comment]
My bad!
The correct repo is https://github.com/kazu-yamamoto/warp-quic
The source of this confusion is a wrong URL in the cabal file.
So, I did:

1. Fix URL in the cabal file and push
2. Update the metadata on Hackage
3. Delete the old repo from Hackage
