### ISSUE TITLE
Unnecessary forever.

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/quic#6]
@ocheron Would you check ef050773ca466d42bbd0a8d13dc5e5ea6c15e4bb?
I think the thread for the second client handshake cannot finish due to this `forever`.
Even after removing this `forever`, my interoperability tests against other implementations also pass.

**Comment by kazu-yamamoto** [comment]
The SHA1 value was wrong. I edited and corrected it.

**Comment by ocheron** [comment]
I added the `forever` in case the TLS library is able to handle several tickets. Normally the thread is killed with `HandshakeDone`.

The `forever` can be removed if this is causing issues, but that means QUIC will not even parse the rest of the handshake messages received.

**Comment by kazu-yamamoto** [comment]
I understand your intention. Thank you!
