### ISSUE TITLE
`quic-0.2.3` doesn't build on GHC < 9.6

### ISSUE THREAD

**Issue by Vlix** [kazu-yamamoto/quic#68]
Because of the use of `threadLabel`, the `base` dependency constraint should be set to `base >= 4.18 && < 5` on `quic-0.2.3`

**Comment by kazu-yamamoto** [comment]
Oh. `threadLabel` is quite new while `lableThread` is old enough.
Uhhhhm.
I should remove `threadLabel` rather than require recent `base`.

**Comment by kazu-yamamoto** [comment]
v0.2.4 has been released which including `#if MIN_VERSION_base(4,18,0)`.
v0.2.3 has been deprecated on Hackage.
