### ISSUE TITLE
Handshake failures and connection state

### ISSUE THREAD

**Issue by ocheron** [kazu-yamamoto/quic#8]
When a TLS handshake failure is caught, an alert is sent to the peer in a `ConnectionCloseQUIC` frame. So I added `setCloseSent` here:
https://github.com/kazu-yamamoto/quic/blob/6df5d6dc22b5f8bc6c472bdda6a97e1f2b8b75c4/Network/QUIC/Handshake.hs#L245

But I notice this has unintended consequence.
`ConnectionState` is an `Ord` instance with `Closing _` greater than `ReadyFor1RTT`.
So when `setCloseSent` is called, some threads start acting like 1-RTT is ready and do their work. But 1-RTT may not be ready after an error occurred.

I think closure state should be kept separate from the other states: connection can be closed during 0-RTT, 1-RTT, or out of any of this.

**Comment by kazu-yamamoto** [comment]
Let's close this.
